// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a segment is attributed to whom it is.
 *
 * ADR-0008 counts visible match attribution among the legibility surfaces
 * it made mandatory in exchange for storing biometrics. An Operator who
 * cannot ask why has no way to know whether to correct it.
 */
export type Attribution = "voiceprint" | "clustered" | "channel" | "operator";
