// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioCheckParams = { 
/**
 * How long to listen. Longer is more conclusive: a refused system-audio
 * permission looks exactly like nobody talking until enough has been
 * played to prove otherwise.
 */
seconds?: number, };
