// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCheckVerdict } from "./AudioCheckVerdict";
import type { AudioLegReport } from "./AudioLegReport";

export type AudioCheckResponse = { legs: Array<AudioLegReport>, verdict: AudioCheckVerdict, 
/**
 * Set when capture could not be started at all, which is a different
 * answer from "started and heard nothing".
 */
couldNotStart?: string, };
