// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioChannel } from "./AudioChannel";
import type { AudioLegState } from "./AudioLegState";

export type AudioLegReport = { channel: AudioChannel, state: AudioLegState, 
/**
 * How much audio arrived on this leg.
 */
milliseconds: number, 
/**
 * The loudest sample seen, 0.0 to 1.0.
 */
peak: number, 
/**
 * What the capture layer said went wrong, when it said anything.
 */
reason?: string, };
