// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one capture leg did during the check.
 */
export type AudioLegState = "working" | "silent" | "notTested" | "nothingCaptured";
