// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which capture leg a segment came from. The mic channel is where the
 * Operator is (ADR-0029 as amended).
 */
export type AudioChannel = "mic" | "system";
