// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the check adds up to. Each surface writes its own words from this:
 * the CLI prints English, the Client looks up a translation.
 */
export type AudioCheckVerdict = "bothLegsWork" | "microphoneWorksOtherUntested" | "oneLegWorks" | "nothingCaptured" | "nothingTested";
