// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BriefingResponse = { 
/**
 * Markdown. The text is the deliverable; rendering it is the Client's.
 */
text: string, 
/**
 * Whether this installation has acknowledged it. Nothing is captured
 * until it has (ADR-0023).
 */
acknowledged: boolean, 
/**
 * True for any version not reviewed by counsel — which is currently
 * all of them, and the surface should say so rather than imply a review
 * that has not happened.
 */
awaitingCounsel: boolean, };
