// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BriefingGetParams = { 
/**
 * `en` or `zh`. Defaults to English, because a translated legal notice
 * shown by accident is worse than an English one shown on purpose.
 */
language?: string, };
