// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the calendar grant is after asking.
 */
export type CalendarAccessResponse = { 
/**
 * True when the Core can read the local calendar store from now on.
 */
granted: boolean, };
