// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which Han script to write Mandarin in.
 *
 * Transcription stays on automatic language detection, because meetings
 * code-switch (story 7) — so the script the model returns is whatever its
 * training data favoured, not what the speaker would have written. Left
 * alone it is frequently Traditional even for a Simplified speaker, which
 * the dogfood run measured. This is the Operator saying which one their
 * record should use; it is an orthographic choice, not a translation, and
 * the words are identical either way.
 */
export type ChineseScript = "simplified" | "traditional";
