// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistorySearchParams } from "./HistorySearchParams";
import type { InitializeParams } from "./InitializeParams";
import type { MeetingDeleteParams } from "./MeetingDeleteParams";
import type { MeetingGetParams } from "./MeetingGetParams";
import type { MeetingListParams } from "./MeetingListParams";
import type { MeetingRetitleParams } from "./MeetingRetitleParams";
import type { MeetingStartParams } from "./MeetingStartParams";
import type { MeetingStopParams } from "./MeetingStopParams";
import type { ModelsFetchParams } from "./ModelsFetchParams";
import type { ModelsStatusParams } from "./ModelsStatusParams";
import type { StatusParams } from "./StatusParams";

/**
 * Every request a Client may send the Core.
 */
export type ClientRequest = { "method": "initialize", "params": InitializeParams } | { "method": "status", "params": StatusParams } | { "method": "meeting/start", "params": MeetingStartParams } | { "method": "meeting/stop", "params": MeetingStopParams } | { "method": "meeting/list", "params": MeetingListParams } | { "method": "meeting/get", "params": MeetingGetParams } | { "method": "meeting/retitle", "params": MeetingRetitleParams } | { "method": "meeting/delete", "params": MeetingDeleteParams } | { "method": "meeting/export", "params": MeetingGetParams } | { "method": "history/search", "params": HistorySearchParams } | { "method": "models/status", "params": ModelsStatusParams } | { "method": "models/fetch", "params": ModelsFetchParams };
