// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientCapabilities = { 
/**
 * Opts the connection into methods marked experimental. Off by default,
 * so a stable Client never sees an unstable surface.
 */
experimentalApi: boolean, };
