// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InitializedParams } from "./InitializedParams";

/**
 * Notifications a Client may send the Core (no response expected).
 */
export type ClientNotification = { "method": "initialized", "params": InitializedParams };
