// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InitializeParams } from "./InitializeParams";
import type { StatusParams } from "./StatusParams";

/**
 * Every request a Client may send the Core.
 */
export type ClientRequest = { "method": "initialize", "params": InitializeParams } | { "method": "status", "params": StatusParams };
