// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Core's coarse, observable state.
 */
export type CoreState = "idle" | "recording";
