// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bulk re-run of History, as far as a Client needs to know about it.
 *
 * The four quantities are kept apart on purpose. `done` counts Meetings
 * walked; `remaining` counts those still owed; `abandoned` counts those
 * cancelling threw away. Nothing folds abandoned work into `done`, because
 * an Operator who stopped a re-run at one of forty should not be told forty
 * were walked.
 */
export type DiarizeRerun = { 
/**
 * The embedding this backlog is for.
 */
model: string, modelVersion: string, 
/**
 * Meetings this re-run owns.
 */
total: number, 
/**
 * Meetings it has walked.
 */
done: number, 
/**
 * Meetings still in line.
 */
remaining: number, 
/**
 * Meetings cancelling gave up on.
 */
abandoned: number, 
/**
 * Whether it was stopped. Work already walked keeps what it concluded.
 */
cancelled: boolean, 
/**
 * Whether a recording is holding the backlog. Bulk work stands aside
 * while a Meeting is being recorded and resumes when it ends, so this
 * is a wait rather than a stop and `remaining` is still owed.
 */
pausedForRecording: boolean, };
