// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiarizeRerun } from "./DiarizeRerun";
import type { DiarizeState } from "./DiarizeState";

export type DiarizeStatusResponse = { state: DiarizeState, 
/**
 * The Meeting being diarized, when one is.
 */
meetingId?: string, doneMs: number, totalMs: number, 
/**
 * The Meetings waiting their turn, in the order they will be worked,
 * the running one first.
 *
 * Additive, so a Client that does not read it sees the running job
 * exactly as it did before (ADR-0028). Empty rather than absent when
 * nothing is queued: a Client drawing a backlog should not have to tell
 * "nothing waiting" from "a Core too old to have a queue".
 */
queued: Array<string>, 
/**
 * The bulk re-run of History a model change owes, when one has been
 * asked for.
 *
 * Absent — not null, not a zeroed block — when no backlog has ever been
 * requested, so a History with no re-run tables and one whose first
 * start merely wrote down which model it uses both serialize exactly as
 * they did before this field existed (ADR-0028).
 */
rerun?: DiarizeRerun, 
/**
 * Why the last start could not check whether the embedding changed,
 * when it could not.
 *
 * **Not the re-run's own failure — the question's.** A model change
 * wipes every Voiceprint in one migration and the next start is what
 * turns that into a re-run; if the check between them fails, the wipe
 * has happened and the walk has not, and nothing else on this response
 * can say so. `rerun` is absent in exactly that case, because a History
 * carrying only the wipe's stamp has requested no backlog, so the
 * message cannot live inside that block.
 *
 * Held for the session rather than in the record: the stamp is
 * untouched by a failure, so the next start asks again and either
 * succeeds or sets this afresh. Absent once a start has got an answer,
 * which is every ordinary installation (ADR-0028).
 */
rerunError?: string, };
