// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bulk re-run of History, as far as a Client needs to know about it.
 *
 * The four quantities are kept apart on purpose. `done` counts Meetings
 * walked; `remaining` counts those still owed; `abandoned` counts those
 * cancelling threw away. Nothing folds abandoned work into `done`, because
 * an Operator who stopped a re-run at one of forty should not be told forty
 * were walked.
 */
export type DiarizeRerun = { 
/**
 * The embedding this backlog is for.
 */
model: string, modelVersion: string, 
/**
 * Meetings this re-run owns.
 */
total: number, 
/**
 * Meetings the backlog is through with: `total` less `remaining` less
 * `abandoned`.
 *
 * **Not "Meetings whose Voiceprints were rebuilt."** It counts a run
 * that committed, a run that could not start at all — no Kept Audio, no
 * models on disk — and a Meeting deleted while it waited. What it leaves
 * out is the two kinds of giving up, which are `abandoned`. So a Client
 * may say processed or finished; it may not promise the walk succeeded.
 */
done: number, 
/**
 * Meetings still in line.
 */
remaining: number, 
/**
 * Meetings cancelling gave up on — this Meeting's own cancel, or the
 * bulk stop. Kept apart from `done` on purpose: nothing was walked.
 */
abandoned: number, 
/**
 * Whether it was stopped. Work already walked keeps what it concluded.
 */
cancelled: boolean, 
/**
 * Whether a recording is holding the backlog. Bulk work stands aside
 * while a Meeting is being recorded and resumes when it ends, so this
 * is a wait rather than a stop and `remaining` is still owed.
 */
pausedForRecording: boolean, };
