// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiarizeState } from "./DiarizeState";

export type DiarizeProgressParams = { meetingId: string, state: DiarizeState, doneMs: number, totalMs: number, };
