// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A re-run of all of History after the embedding changed.
 *
 * An unannounced multi-hour job that reprocesses everything is, from
 * outside, indistinguishable from the product misbehaving — so it is
 * reported whether or not anyone asked for it.
 */
export type DiarizeRerunStatus = { 
/**
 * Meetings walked so far, out of `total`.
 */
done: number, total: number, 
/**
 * Standing down because a Meeting is being recorded. The backlog is
 * hours of two neural models, and the recording comes first.
 */
paused: boolean, 
/**
 * Stopped by the Operator. Every Meeting already walked keeps what that
 * walk concluded.
 */
cancelled: boolean, 
/**
 * Named Speakers whose Voiceprint the re-run has earned back.
 */
relearned: number, 
/**
 * Named Speakers still without one: voices History knows by name and
 * can no longer recognize. Reported rather than left to be discovered
 * the next time one of them is not identified.
 */
withoutVoiceprint: number, 
/**
 * Pseudonymous Speakers after the re-run. A re-run re-mints them, so
 * "Speaker 3" is not the Speaker 3 anyone saw before it — which the
 * Operator should be told rather than notice.
 */
pseudonyms: number, };
