// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiarizeState } from "./DiarizeState";

export type DiarizeStatusResponse = { state: DiarizeState, 
/**
 * The Meeting being diarized, when one is.
 */
meetingId?: string, doneMs: number, totalMs: number, };
