// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a diarization job is doing.
 */
export type DiarizeState = "idle" | "running" | "unavailable";
