// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchResult } from "./SearchResult";

export type HistorySearchResponse = { results: Array<SearchResult>, };
