// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerCapabilities } from "./ServerCapabilities";
import type { ServerInfo } from "./ServerInfo";

export type InitializeResponse = { serverInfo: ServerInfo, capabilities: ServerCapabilities, };
