// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonRpcErrorBody } from "./JsonRpcErrorBody";
import type { RequestId } from "./RequestId";

/**
 * A response indicating the request failed.
 */
export type JsonRpcError = { id: RequestId, error: JsonRpcErrorBody, };
