// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonRpcError } from "./JsonRpcError";
import type { JsonRpcNotification } from "./JsonRpcNotification";
import type { JsonRpcRequest } from "./JsonRpcRequest";
import type { JsonRpcResponse } from "./JsonRpcResponse";

/**
 * Any valid protocol object that can be decoded off the wire or encoded onto it.
 */
export type JsonRpcMessage = JsonRpcRequest | JsonRpcResponse | JsonRpcError | JsonRpcNotification;
