// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestId } from "./RequestId";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A request that expects a response.
 */
export type JsonRpcRequest = { id: RequestId, method: string, params?: JsonValue, };
