// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeetingSetNotesParams = { id: string, 
/**
 * Markdown. Replaces whatever was there — Notes are the Operator's, and
 * a merge would be the product having an opinion about their writing.
 */
notes: string, };
