// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recorded session: the unit of storage, retrieval, and summary.
 */
export type Meeting = { 
/**
 * UUIDv7. Its first 8 hex characters appear in the Mirror's filename
 * and are the stable handle outside references should key on.
 */
id: string, startedAt: string, endedAt?: string, 
/**
 * None until titled. Clients render the fallback rather than inventing
 * a title, so "untitled" never becomes a stored string.
 */
title?: string, 
/**
 * The app detection attributed this Meeting to; the Mirror's slug
 * before a Title exists.
 */
detectedApp?: string, durationSeconds?: number, mirrorFilename?: string, audioPath?: string, };
