// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Meeting } from "./Meeting";
import type { MeetingChangeKind } from "./MeetingChangeKind";

export type MeetingChangedParams = { kind: MeetingChangeKind, meetingId: string, 
/**
 * Absent for a deletion.
 */
meeting?: Meeting, };
