// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened to a Meeting.
 */
export type MeetingChangeKind = "started" | "updated" | "stopped" | "deleted";
