// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Meeting } from "./Meeting";

export type MeetingResponse = { meeting: Meeting, };
