// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recorded session: the unit of storage, retrieval, and summary.
 */
export type Meeting = { 
/**
 * UUIDv7. Its first 8 hex characters appear in the Mirror's filename
 * and are the stable handle outside references should key on.
 */
id: string, startedAt: string, endedAt?: string, 
/**
 * None until titled. Clients render the fallback rather than inventing
 * a title, so "untitled" never becomes a stored string.
 */
title?: string, 
/**
 * The calendar event this Meeting was armed from, when one named it
 * (ADR-0036). Kept so the record can say *which* scheduled meeting
 * this was, not merely that it had a title.
 */
calendarEventId?: string, 
/**
 * Who the event invited. **Stored, not applied**: these become
 * Speaker-naming suggestions in M3, and turning an invitation into an
 * attribution before Diarization exists would be inventing who spoke.
 */
calendarAttendees?: Array<string>, 
/**
 * The Operator's own writing (ADR-0018). **The one mutable thing here**
 * — the Transcript and its attribution are what happened and never
 * change, while Notes are what the Operator chose to write and stay
 * editable forever.
 */
notes?: string, 
/**
 * The generated Summary, as markdown. Derived rather than observed, so
 * regenerating it destroys nothing.
 */
summary?: string, 
/**
 * Which Backend produced the Summary. An Operator who chose Cloud and
 * got local quality is owed the reason (story 38); one who chose Local
 * is owed evidence that is what ran.
 */
summaryBackend?: string, 
/**
 * What this Summary could not cover, when chunks of the Meeting failed.
 * Additive and optional (ADR-0028): a Client that predates it sees a
 * Meeting exactly as before.
 */
summaryGaps?: string, summaryGeneratedAt?: string, 
/**
 * The app detection attributed this Meeting to; the Mirror's slug
 * before a Title exists.
 */
detectedApp?: string, durationSeconds?: number, mirrorFilename?: string, audioPath?: string, 
/**
 * What this recording lost, in the Operator's terms — a capture leg that
 * never started, one that died partway, audio that would not encode.
 *
 * Empty for a whole recording. This is in the record rather than only in
 * a log because a Meeting missing half its audio is otherwise
 * indistinguishable from one where nobody spoke, and the Operator finds
 * out by reading a transcript that makes no sense.
 */
audioNotes?: Array<string>, };
