// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recorded session: the unit of storage, retrieval, and summary.
 */
export type Meeting = { 
/**
 * UUIDv7. Its first 8 hex characters appear in the Mirror's filename
 * and are the stable handle outside references should key on.
 */
id: string, startedAt: string, endedAt?: string, 
/**
 * None until titled. Clients render the fallback rather than inventing
 * a title, so "untitled" never becomes a stored string.
 */
title?: string, 
/**
 * The app detection attributed this Meeting to; the Mirror's slug
 * before a Title exists.
 */
detectedApp?: string, durationSeconds?: number, mirrorFilename?: string, audioPath?: string, 
/**
 * What this recording lost, in the Operator's terms — a capture leg that
 * never started, one that died partway, audio that would not encode.
 *
 * Empty for a whole recording. This is in the record rather than only in
 * a log because a Meeting missing half its audio is otherwise
 * indistinguishable from one where nobody spoke, and the Operator finds
 * out by reading a transcript that makes no sense.
 */
audioNotes?: Array<string>, };
