// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelProgressParams = { 
/**
 * Registry key of the model being fetched.
 */
key: string, displayName: string, doneBytes: number, totalBytes: number, 
/**
 * Set when the fetch ended without finishing — cancelled, or failed.
 * A download that stops is not the same as one still running at the
 * same byte count, and a Client showing a frozen bar cannot tell them
 * apart.
 */
stopped?: string, };
