// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelState } from "./ModelState";

export type ModelsStatusResponse = { models: Array<ModelState>, 
/**
 * True when everything required is present and verified — the gate the
 * tray's not-ready state and any capture attempt read.
 */
ready: boolean, };
