// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelsFetchParams = { 
/**
 * Fetch one model by key; omit to fetch everything required.
 */
key?: string, };
