// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelAvailability } from "./ModelAvailability";

export type ModelState = { key: string, displayName: string, state: ModelAvailability, required: boolean, totalBytes: number, bytesOnDisk?: number, path?: string, 
/**
 * Why a model is corrupted, when it is.
 */
detail?: string, };
