// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostureClaim } from "./PostureClaim";
import type { TrafficEntry } from "./TrafficEntry";

export type PostureResponse = { historyDir: string, meetings: number, speakers: number, 
/**
 * How many Speakers have a stored Voiceprint — the biometric count, as
 * a number rather than a category.
 */
voiceprints: number, models: Array<string>, calendarGranted: boolean, traffic: Array<TrafficEntry>, foreclosed: Array<PostureClaim>, 
/**
 * Where a guarantee moved, and which decision moved it. Shown, not
 * absorbed: a page reflecting only the current state, with no sign the
 * promise had changed, is what an evaluator trusts least.
 */
amended: Array<PostureClaim>, 
/**
 * True when this installation would make no network call at all.
 */
currentlySilent: boolean, source: string, };
