// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A capability foreclosed, or one whose promise moved, with where to check.
 */
export type PostureClaim = { capability: string, proof: string, };
