// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerInfo = { name: string, version: string, 
/**
 * Wire-protocol version. Bumped only on a breaking change (ADR-0028
 * keeps changes additive, so this is expected to stay at 1).
 */
protocolVersion: number, };
