// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerCapabilities = { 
/**
 * True when the Core granted the connection's experimental-API request.
 */
experimentalApi: boolean, };
