// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreStateChangedParams } from "./CoreStateChangedParams";
import type { DiarizeProgressParams } from "./DiarizeProgressParams";
import type { MeetingChangedParams } from "./MeetingChangedParams";
import type { SpeakerChangedParams } from "./SpeakerChangedParams";
import type { TranscriptCaptionsDroppedParams } from "./TranscriptCaptionsDroppedParams";
import type { TranscriptSegmentAddedParams } from "./TranscriptSegmentAddedParams";

/**
 * Everything the Core may push to an attached Client unprompted.
 */
export type ServerNotification = { "method": "core/stateChanged", "params": CoreStateChangedParams } | { "method": "meeting/changed", "params": MeetingChangedParams } | { "method": "transcript/segmentAdded", "params": TranscriptSegmentAddedParams } | { "method": "transcript/captionsDropped", "params": TranscriptCaptionsDroppedParams } | { "method": "speaker/changed", "params": SpeakerChangedParams } | { "method": "diarize/progress", "params": DiarizeProgressParams };
