// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreStateChangedParams } from "./CoreStateChangedParams";

/**
 * Everything the Core may push to an attached Client unprompted.
 */
export type ServerNotification = { "method": "core/stateChanged", "params": CoreStateChangedParams };
