// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChineseScript } from "./ChineseScript";

export type SettingsResponse = { briefingAcknowledged: boolean, launchAtLogin: boolean, autoRecord: boolean, chineseScript: ChineseScript, 
/**
 * Where the login-item registration lives, so the Operator can see and
 * remove it by hand.
 */
launchAtLoginLocation: string, 
/**
 * True when the setting and the actual registration disagree — for
 * example after the Operator deleted the plist themselves.
 */
launchAtLoginRegistered: boolean, 
/**
 * The Summary Knob. Absent means unchosen (ADR-0013).
 */
summaryBackend?: string, summaryStrict: boolean, summaryCloudWarningAccepted: boolean, 
/**
 * The Operator's system prompt, when they have edited it. Absent means
 * the default is in use, which is what makes reset a deletion.
 */
summaryPrompt?: string, 
/**
 * The default, so a Client can show it and offer reset without keeping
 * its own copy that could drift.
 */
summaryPromptDefault: string, 
/**
 * Whether the update check may run. With this off and models present,
 * the product makes no network calls at all (ADR-0034).
 */
checkForUpdates: boolean, };
