// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChineseScript } from "./ChineseScript";

export type SettingsSetParams = { 
/**
 * Records that the Operator acknowledged the Briefing. Once true it is
 * never set back to false by a Client: un-acknowledging consent is not
 * a thing that happens, and allowing it would make the pre-capture
 * invariant a toggle.
 */
briefingAcknowledged?: boolean, 
/**
 * Registration only — this changes the *next* login and leaves a
 * running Core alone (story 9c).
 */
launchAtLogin?: boolean, autoRecord?: boolean, 
/**
 * Which Han script Mandarin is written in. See [`ChineseScript`].
 */
chineseScript?: ChineseScript, };
