// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsResponse = { briefingAcknowledged: boolean, launchAtLogin: boolean, autoRecord: boolean, 
/**
 * Where the login-item registration lives, so the Operator can see and
 * remove it by hand.
 */
launchAtLoginLocation: string, 
/**
 * True when the setting and the actual registration disagree — for
 * example after the Operator deleted the plist themselves.
 */
launchAtLoginRegistered: boolean, };
