// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeakerRenameParams = { id: string, displayName: string, 
/**
 * Consent to fold this Speaker into the one already holding the name.
 *
 * Absent or false, a rename onto a name History already holds does
 * nothing and comes back describing what a join would merge, so the
 * Client can ask. Combining two identities should be a decision, not a
 * side effect of typing (ADR-0037).
 */
join?: boolean | null, };
