// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Speaker, as the Voice Registry shows it.
 */
export type Speaker = { id: string, 
/**
 * Absent until the Operator names it. Clients render a numbered
 * pseudonym ("Speaker 3"); it is deliberately not stored, because a
 * stored pseudonym looks like a name someone chose.
 */
displayName?: string, 
/**
 * The Operator's own Speaker, displayed "You" (ADR-0029 as amended).
 */
isOperator: boolean, 
/**
 * Whether the app can still recognize this voice. False after a
 * Voiceprint deletion, with the Speaker and the record intact.
 */
hasVoiceprint: boolean, 
/**
 * Set when the Operator named this Speaker: naming is confirmation
 * (ADR-0008 as amended), and a confirmed Voiceprint outranks an
 * unconfirmed one when matching.
 */
confirmed: boolean, 
/**
 * Which model produced the stored Voiceprint. Present so a Registry can
 * explain why an upgrade re-embedded, rather than recognition silently
 * changing quality.
 */
voiceprintModel?: string, meetingsSeenIn: number, 
/**
 * When this voice was first captured: the start of the earliest Meeting
 * it was heard in.
 */
firstSeenAt?: string, 
/**
 * That Meeting's id, so a Client can open the recording the voice was
 * taken from rather than only naming it.
 */
firstMeetingId?: string, 
/**
 * The title of that Meeting, when it has one. Absent rather than
 * "Untitled", which is a Client's word and not a stored fact.
 */
firstMeetingTitle?: string, 
/**
 * The app that Meeting was detected in. Sent beside the title because
 * most Meetings are auto-detected and never titled, and "Teams, 8 Sep"
 * answers *which meeting* where "Untitled" does not.
 */
firstMeetingApp?: string, 
/**
 * When this voice was last heard: the start of the most recent Meeting
 * it appears in. Equal to `first_seen_at` for a voice heard once.
 */
lastHeardAt?: string, createdAt: string, };
