// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a recording was not taken as an identity.
 *
 * Kept apart rather than collapsed into one message because each sends the
 * Operator somewhere different: `Silent` to System Settings, `MoreThanOneVoice`
 * to a quieter room, `TooLittleSpeech` back to the button.
 */
export type SpeakerEnrolRefusal = "silent" | "tooLittleSpeech" | "moreThanOneVoice" | "nothingEmbeddable" | "couldNotRecord";
