// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpeakerSampleClip } from "./SpeakerSampleClip";

/**
 * A few seconds of one voice, ready to play.
 */
export type SpeakerSampleResponse = { 
/**
 * Absent when nothing can be played: the Speaker predates kept
 * samples, or the recording it was cut from is gone. Not an error —
 * Voiceprints outlive the audio they came from (ADR-0009), and a Client
 * shows the row either way.
 */
sample?: SpeakerSampleClip, };
