// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Speaker } from "./Speaker";
import type { SpeakerJoinPreview } from "./SpeakerJoinPreview";

export type SpeakerResponse = { speaker: Speaker, 
/**
 * Present when the rename was **not** applied because the name belongs
 * to another Speaker. `speaker` is then unchanged, and repeating the
 * call with `join: true` performs the merge this describes.
 */
joinRequired?: SpeakerJoinPreview | null, };
