// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeakerEnrolment = { speakerId: string, durationMs: number, recordedAt: string, 
/**
 * Whether the enrolment is the Operator's identity *right now*. False in
 * the window after a voice-model change, where the recording is still
 * here and the vectors taken from it are not — the Core mints them again
 * on the next start, and until it does the Operator is recognized the
 * old way.
 */
active: boolean, };
