// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Speaker } from "./Speaker";
import type { SpeakerEnrolRefusal } from "./SpeakerEnrolRefusal";

export type SpeakerEnrolResponse = { accepted: boolean, 
/**
 * Absent when accepted.
 */
refusal?: SpeakerEnrolRefusal, 
/**
 * What the capture layer said, when it said anything. For the log and
 * for a Client that wants to show the machine's own words.
 */
detail?: string, 
/**
 * How much of the recording was speech.
 */
voicedMs: number, 
/**
 * How many voices were heard in it. More than one is a refusal.
 */
voicesHeard: number, 
/**
 * The Operator, as they now stand. Absent on a refusal, which changes
 * nothing.
 */
speaker?: Speaker, };
