// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpeakerEnrolment } from "./SpeakerEnrolment";

export type SpeakerEnrolmentResponse = { 
/**
 * Absent when the Operator has never enrolled, which is every
 * installation that skipped the step.
 */
enrolment?: SpeakerEnrolment, };
