// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Speaker, as the Voice Registry shows it.
 */
export type Speaker = { id: string, 
/**
 * Absent until the Operator names it. Clients render a numbered
 * pseudonym ("Speaker 3"); it is deliberately not stored, because a
 * stored pseudonym looks like a name someone chose.
 */
displayName?: string, 
/**
 * The Operator's own Speaker, displayed "You" (ADR-0029 as amended).
 */
isOperator: boolean, 
/**
 * Whether the app can still recognize this voice. False after a
 * Voiceprint deletion, with the Speaker and the record intact.
 */
hasVoiceprint: boolean, 
/**
 * Set when the Operator named this Speaker: naming is confirmation
 * (ADR-0008 as amended), and a confirmed Voiceprint outranks an
 * unconfirmed one when matching.
 */
confirmed: boolean, 
/**
 * Which model produced the stored Voiceprint. Present so a Registry can
 * explain why an upgrade re-embedded, rather than recognition silently
 * changing quality.
 */
voiceprintModel?: string, meetingsSeenIn: number, firstSeenAt?: string, createdAt: string, };
