// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeakerEnrolParams = { 
/**
 * How long to listen. Longer is better evidence and worse to sit
 * through; the Core clamps whatever arrives.
 */
seconds?: number, };
