// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Meeting a Speaker was heard in: enough to name it and to open it, and
 * nothing else. A whole `Meeting` would carry that Meeting's Notes and
 * Summary to draw one line of a list.
 */
export type SpeakerMeeting = { id: string, startedAt: string, title?: string, detectedApp?: string, };
