// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Speaker } from "./Speaker";

export type SpeakerDetailResponse = { speaker: Speaker, 
/**
 * Names the calendar knew about for Meetings this Speaker appears in,
 * offered as candidates. **Suggestions only** — an invitation is
 * evidence about who was invited, never about who spoke, and applying
 * one automatically would invent attribution.
 */
nameSuggestions: Array<string>, };
