// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Speaker } from "./Speaker";
import type { SpeakerMeeting } from "./SpeakerMeeting";

export type SpeakerDetailResponse = { speaker: Speaker, 
/**
 * Every Meeting this Speaker was heard in, newest first — what the
 * Registry's Meeting count expands to.
 *
 * Sent here rather than on [`Speaker`] because the list response carries
 * every Speaker at once, and a Registry that shows counts should not pay
 * for every Meeting behind every one of them to draw itself.
 */
meetings: Array<SpeakerMeeting>, 
/**
 * Names the calendar knew about for Meetings this Speaker appears in,
 * offered as candidates. **Suggestions only** — an invitation is
 * evidence about who was invited, never about who spoke, and applying
 * one automatically would invent attribution.
 */
nameSuggestions: Array<string>, };
