// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioChannel } from "./AudioChannel";

export type SpeakerSampleClip = { 
/**
 * The clip, base64 of the bytes `mime_type` names. Inline rather than
 * a path because the renderer never sees the record or a file path
 * (ADR-0026), and a clip is a few tens of kilobytes.
 */
audioBase64: string, mimeType: string, 
/**
 * Where it was cut from, so a Client can open that Meeting.
 */
meetingId: string, channel: AudioChannel, startMs: number, endMs: number, };
