// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Speaker } from "./Speaker";

/**
 * What a rename would merge, when the name is already taken.
 */
export type SpeakerJoinPreview = { 
/**
 * The Speaker that already holds the name, and would survive.
 */
into: Speaker, 
/**
 * Meetings the surviving Speaker has been heard in.
 */
intoMeetings: number, 
/**
 * Meetings the Speaker being named has been heard in.
 */
fromMeetings: number, };
