// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreState } from "./CoreState";

export type StatusResponse = { version: string, pid: number, uptimeSeconds: number, state: CoreState, 
/**
 * Absolute path of the History folder this Core writes to.
 */
historyDir: string, 
/**
 * Set when the History folder has Mirrors but no machine store —
 * an incomplete copy (ADR-0035).
 */
incompleteCopyWarning?: string, };
