// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SummarySetKeyParams = { provider: string, 
/**
 * None clears the stored key. Clearing is a first-class act, not a side
 * effect of switching the Knob.
 */
key?: string, };
