// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SummaryDataHandling } from "./SummaryDataHandling";

/**
 * What is known about one Summary destination.
 */
export type SummaryBackendOption = { id: string, displayName: string, 
/**
 * Whether choosing this sends meeting content off the machine. The one
 * fact this screen exists to make unmissable.
 */
leavesTheMachine: boolean, 
/**
 * Whether a key is stored for it. **Never the key itself** — a settings
 * screen that can display one can leak it into a screenshot.
 */
hasKey: boolean, 
/**
 * Absent for local destinations, where there is nothing to characterise.
 */
dataHandling?: SummaryDataHandling, };
