// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A provider's stated data handling (ADR-0010). Information, never a gate.
 */
export type SummaryDataHandling = { trainsOnInputs: boolean, retention: string, zeroRetentionAvailable: boolean, 
/**
 * When a human last read the terms. `unverified` means nobody has, and
 * the surface should say so rather than implying a check that did not
 * happen.
 */
verifiedOn: string, };
