// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SummaryBackendOption } from "./SummaryBackendOption";

export type SummaryBackendsResponse = { options: Array<SummaryBackendOption>, 
/**
 * What the Operator chose. **Absent means nobody has chosen**
 * (ADR-0013) — a state to show, not to default away.
 */
chosen?: string, strict: boolean, cloudWarningAccepted: boolean, 
/**
 * The custom endpoint label (ADR-0010).
 */
customEndpointLabel: string, };
