// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One thing this product may say on the network (ADR-0034). Three, closed.
 */
export type TrafficEntry = { name: string, host: string, whatItSends: string, 
/**
 * Whether it can happen right now, as configured.
 */
enabled: boolean, disableable: boolean, };
