// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attribution } from "./Attribution";
import type { AudioChannel } from "./AudioChannel";

/**
 * One attributed span of the Transcript.
 */
export type TranscriptSegment = { id: string, sequence: number, channel: AudioChannel, startMs: number, endMs: number, text: string, 
/**
 * Set by Diarization in M3. Until then the channel carries attribution.
 */
speakerId?: string, 
/**
 * Why `speaker_id` is what it is (ADR-0008's visible match
 * attribution). Absent on segments written before Diarization ran.
 */
attribution?: Attribution, };
