// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Meeting } from "./Meeting";
import type { TranscriptSegment } from "./TranscriptSegment";

export type TranscriptSnapshotResponse = { 
/**
 * None when nothing is recording and no Meeting was named.
 */
meeting?: Meeting, 
/**
 * Everything transcribed so far. Live segments arrive as notifications
 * from the moment this response is produced.
 */
segments: Array<TranscriptSegment>, subscribed: boolean, };
