// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TranscriptSubscribeParams = { 
/**
 * Which Meeting to follow. Omit for the one currently recording.
 */
meetingId?: string, };
