// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchlistKind } from "./WatchlistKind";

export type WatchlistAddParams = { id: string, 
/**
 * Omitted for a suggested entry, whose name the Core already knows.
 */
name?: string, kind?: WatchlistKind, };
