// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchlistEntry } from "./WatchlistEntry";

export type WatchlistResponse = { 
/**
 * What is watched, in a stable order.
 */
entries: Array<WatchlistEntry>, 
/**
 * Known call apps offered but not watched — WeChat ships here rather
 * than on the list, because default-recording personal calls is the
 * posture ADR-0030 declined.
 */
suggestions: Array<WatchlistEntry>, };
