#!/usr/bin/env bash
#
# Generates the Homebrew cask and the winget manifest from real artifacts.
#
# **Generated, never hand-edited.** A checksum maintained by hand is one that
# will eventually be wrong, and the failure mode of a wrong checksum in a
# package manager is an install that refuses with a message about tampering.
#
# Needs a tagged release: both files point at release URLs, so neither can
# be produced before one exists. Run after `build.sh`, with the tag.
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: $0 <version>   # e.g. 0.1.0, matching the git tag v0.1.0" >&2
  exit 2
fi

version="$1"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$root/packaging/out"
repo="EverTranscript/EverTranscript"

if [[ ! -f "$out/SHA256SUMS" ]]; then
  echo "no artifacts: run packaging/build.sh first" >&2
  exit 1
fi

macos_artifact="EverTranscript-${version}-macos.zip"
windows_artifact="EverTranscript-${version}-windows.exe"

sum_for() {
  # From the build's own SHA256SUMS, so the manifest cannot disagree with
  # what was actually built.
  awk -v want="./$1" '$2 == want { print $1 }' "$out/SHA256SUMS" | head -1
}

macos_sum="$(sum_for "$macos_artifact")"
windows_sum="$(sum_for "$windows_artifact")"

if [[ -z "$macos_sum" ]]; then
  echo "warning: $macos_artifact is not in SHA256SUMS — writing a placeholder" >&2
  echo "         the cask will be rejected until a real release artifact exists" >&2
  macos_sum="REPLACE_WITH_RELEASE_ARTIFACT_SHA256"
fi
if [[ -z "$windows_sum" ]]; then
  echo "warning: $windows_artifact is not in SHA256SUMS — writing a placeholder" >&2
  windows_sum="REPLACE_WITH_RELEASE_ARTIFACT_SHA256"
fi

mkdir -p "$out/dist"

cat > "$out/dist/evertranscript.rb" <<CASK
# Generated by packaging/make-manifests.sh — do not hand-edit.
cask "evertranscript" do
  version "${version}"
  sha256 "${macos_sum}"

  url "https://github.com/${repo}/releases/download/v#{version}/EverTranscript-#{version}-macos.zip"
  name "EverTranscript"
  desc "Local-first meeting notetaker that never misses a meeting"
  homepage "https://github.com/${repo}"

  depends_on macos: ">= :sonoma"

  app "EverTranscript.app"
  binary "#{appdir}/EverTranscript.app/Contents/Resources/evertranscript"

  uninstall quit:      "com.evertranscript.core",
            launchctl: "com.evertranscript.core",
            delete:    "#{appdir}/EverTranscript.app"

  # Deliberately NOT zapping the History folder (ADR-0035). It is the
  # Operator's record and the complete portable unit — transcripts, audio and
  # voice profiles — and deleting it because somebody switched machines would
  # be the most destructive thing this product could do. Models and caches go;
  # the record stays.
  zap trash: [
    "~/Library/Application Support/EverTranscript/models",
    "~/Library/Logs/EverTranscript",
  ]

  caveats <<~EOS
    Your recordings stay in ~/Documents/EverTranscript and are not removed by
    uninstalling. That folder contains transcripts, audio, and voice profiles;
    delete it yourself if you want them gone.
  EOS
end
CASK

mkdir -p "$out/dist/winget"
cat > "$out/dist/winget/EverTranscript.EverTranscript.installer.yaml" <<WINGET
# Generated by packaging/make-manifests.sh — do not hand-edit.
PackageIdentifier: EverTranscript.EverTranscript
PackageVersion: ${version}
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/${repo}/releases/download/v${version}/EverTranscript-${version}-windows.exe
    InstallerSha256: ${windows_sum}
ManifestType: installer
ManifestVersion: 1.6.0
WINGET

cat > "$out/dist/winget/EverTranscript.EverTranscript.locale.en-US.yaml" <<WINGET
# Generated by packaging/make-manifests.sh — do not hand-edit.
PackageIdentifier: EverTranscript.EverTranscript
PackageVersion: ${version}
PackageLocale: en-US
Publisher: EverTranscript
PackageName: EverTranscript
License: Apache-2.0
ShortDescription: Local-first meeting notetaker that never misses a meeting
Description: |-
  Records, transcribes and diarizes meetings entirely on your machine.
  Uninstalling does not remove your recordings: they live in
  Documents\\EverTranscript and include transcripts, audio, and voice
  profiles. Delete that folder yourself if you want them gone.
ManifestType: defaultLocale
ManifestVersion: 1.6.0
WINGET

cat > "$out/dist/winget/EverTranscript.EverTranscript.yaml" <<WINGET
# Generated by packaging/make-manifests.sh — do not hand-edit.
PackageIdentifier: EverTranscript.EverTranscript
PackageVersion: ${version}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
WINGET

echo "wrote:"
find "$out/dist" -type f | sed 's|^|  |'
echo
echo "Publishing needs accounts and a tagged release, and is the Operator's:"
echo "  homebrew — open a PR to a tap with out/dist/evertranscript.rb"
echo "  winget   — open a PR to microsoft/winget-pkgs with out/dist/winget/"
